### ISSUE TITLE
Using google's location api for location updates.

### ISSUE THREAD

**Issue by Oitzu** [Oitzu/pimatic-location#4]
The location documentation https://developer.android.com/guide/topics/location/strategies.html suggests: "In most cases, you'll get better battery performance, as well as more appropriate accuracy, by using the Location Services API."
The Location Services API allows to adjust the location updates based on user’s modality (still, walking, driving, and so on). 
https://developer.android.com/google/play-services/location.html

It will be tested if pimatic-location can use this to lower battery usage.

**Comment by Oitzu** [comment]
@sebastienvg could you test the newest dev-version? 
The readme.md is still a little messy but please note that you need to configure the pimatic plugin "pimatic-location" and (a) device(s) for the latest dev-version.

About the new priority setting:
Read here what the different settings cause to location updates.

Both the interval and the priority should be configureable by tasker. (See: "Tasker integration")

**Comment by sebastienvg** [comment]
I like the way this project goes @Oitzu I'll try the new dev-version as soon as pimatic-location is installed ;)

**Comment by sebastienvg** [comment]
after the last update I made the changes to the config.json with long and lat for each devices and I get this at startup

`coffee-cache: compiling coffee-script file "pimatic-location.coffee"...Done
13:59:27.208 [pimatic] error: Cannot find module 'googlemapsutil'`

`npm install googlemapsutil` from the node_modules dir resolved the issue.

**Comment by Oitzu** [comment]
Strange I thought npm would install this automatically at the update. You
could either install the missing module with 'npm install googlemapsutil'
or reinstall the pimatic-location plugin.
Am 21.02.2015 20:02 schrieb "Sebastien Vayrette-Gavard" <
notifications@github.com>:

**Comment by Oitzu** [comment]
The latest update will bring also a new dependencie "geolib".
Make sure to update the app from dev also. It should now also support route distance, eta and current location (by text).
I changed the approach to sending the current location to the plugin and let the plugin calculate the rest of it instead of calculating it on the smartphone.

As soon this is tested i will clean a little bit up and merge it to master.

**Comment by sweetpi** [comment]
Very nice work! 

It would be cool if using google for routing would be optional, so you can turn it off, if you don't want to share your location with google.

Can't wait to try it after the clean up.

**Comment by Oitzu** [comment]
@sweetpi nice idea. :)
I'm definitely looking into it.
I'm still searching for the best way to optimize the display of the values in Pimatic.
Current:
https://www.dropbox.com/s/je5mbszzssubgh2/Screenshot%202015-02-22%2012.07.02.png?dl=0

Would be nice to:
1.) Only show values you want to show.
2.) Only show Graphs at values you want Graphs
3.) Convert values to more meaningful values. (Over 1000m show 1,x km..; over 60 seconds show 1m xxmin.)

@sweetpi as this is my first coffescript could you have a look at:
https://github.com/Oitzu/pimatic-location-plugin/blob/master/pimatic-location.coffee ?
A few things disturbing me:
1.) Your example shown @_Var = var to resolve an promise but only "@emit 'Var', var" worked for me. Whats the correct way?
2.) As seen in line 34, 35 i declared some variables in the class scope and set values to them in line 101 (constructor) and 142 (action handler) to use them in die googleapi callback method beginning at line 110. Is there a better way to do this?

**Comment by sweetpi** [comment]
> 1.) Only show values you want to show.

There's currently no issue solution, I need to add an option for the attribute here.

> 2.) Only show Graphs at values you want Graphs

You can set `displaySparkline: false` for the attributes you don't want to have a graph behind it.

> 3.) Convert values to more meaningful values. (Over 1000m show 1,x km..; over 60 seconds show 1m xxmin.)

I've to add some more prefixes here: https://github.com/pimatic/pimatic-mobile-frontend/blob/master/app/scope.coffee#L28-L32

> 1.) Your example shown @_Var = var to resolve an promise but only "@emit 'Var', var" worked for me. Whats the correct way?

```
@emit 'var', var
```

emits an update event for the value that is send to the frontend and to the rule engine. So it has nothing to do with promises.

```
@_Var = var
```

is the same as: `this._var = var` so a assignment to a local property of a device. This is only needed so that the corresponding getter can always return the most up to date value. So just some coffeescript syntax sugar here, no promises involved.

In node.js there are two common ways to return values from async functions. Callbacks and promises. pimatic uses promises because they lead to less errors and simplify error handling a lot. All getter-functions of devices are async by default and so must return a promise, because they could involve a async network request (for example get online weather information) or requesting a value from a physical device. So your getter could request the value from your phone to return the most up-to-date value. But we don't want to do this, because we don't really need it and it would be to complicated. We just return the last value we receive from the phone, what we saved to the local property. But we have to wrap the cached value in an (resolved) Promise using `Promise.resolve(@var)`.

> 2.) As seen in line 34, 35 i declared some variables in the class scope and set values to them in line 101 (constructor) and 142 (action handler) to use them in die googleapi callback method beginning at line 110. Is there a better way to do this?

In coffee-script you don't need to assign `this` to a variable to access it inside a callback function ('_this = this'). You can simply use the fat arrow instead: http://coffeescript.org/#fat-arrow

Use the fat arrow instead and you can use just `this` or the `@`-notation inside the callback. It's best to use a closure for the `updateLocationCB`-callback inside the `updateLocation`-function. Then you can just access `addressUpdate` inside the callback.` and don't have to expose it to outer scopes.

One small thing:

Please use attribute names starting with a lowercase letter, because all other plugins do that.

**Comment by Oitzu** [comment]
@sweetpi you can give it a try if you want. Merged the dev branch to master.
Use 'useGoogleMaps: false' in the device-config if you want to disable the GoogleMaps Support. (Disabling the features route distance, eta and current address)

Though... i didn't get the callback working like you described... do you want to create a pull request for that?

Are there any open issues for points 1 - 3, to track?
